### ISSUE TITLE
Deta couldn't find the project

### ISSUE THREAD

**Issue by watahisho3** [PyTsun/LegoProxy#1]
When I click click the deploy button Deta couldn't find the project I don't know what it means cuz its my first time using it

**Comment by PyTsun** [comment]
can you try using this link?
https://web.deta.sh/deploy?path=https://github.com/PyTsun/LegoProxy

**Comment by watahisho3** [comment]
thanks its working now

**Comment by PyTsun** [comment]
glad it helped!
