### ISSUE TITLE
Apis that use the ? in URLs do not parse info

### ISSUE THREAD

**Issue by Tamasina07** [PyTsun/LegoProxy#2]
As said in title, any API that uses ?s in the url does not work.

Intended result: https://games.roblox.com/v1/games?universeIds=13058
`{
  "data": [
    {
      "allowedGearCategories": [],
      "allowedGearGenres": [
        "Ninja"
      ],
      "copyingAllowed": true,
      "createVipServersAllowed": false,
      "created": "2007-05-01T01:07:04.78Z",
      "creator": {
        "hasVerifiedBadge": true,
        "id": 1,
        "isRNVAccount": false,
        "name": "Roblox",
        "type": "User"
      },
      "description": "The classic ROBLOX level is back!",
      "favoritedCount": 201879,
      "genre": "Fighting",
      "id": 13058,
      "isAllGenre": false,
      "isFavoritedByUser": false,
      "isGenreEnforced": true,
      "maxPlayers": 8,
      "name": "Classic: Crossroads",
      "playing": 12,
      "price": null,
      "rootPlaceId": 1818,
      "sourceDescription": "The classic ROBLOX level is back!",
      "sourceName": "Classic: Crossroads",
      "studioAccessToApisAllowed": false,
      "universeAvatarType": "MorphToR6",
      "updated": "2017-09-26T22:43:21.667Z",
      "visits": 9119592
    }
  ]
}`
Actual result: https://legoproxy.veriblox.ml/games/v1/games?universeIds=13508
`{"errors":[{"code":8,"message":"No universe IDs were specified.","userFacingMessage":"Something went wrong"}]}`

**Comment by Thomasluigi07** [comment]
This also happens with the Thumbnails api which uses multiple parameters.
Intended result: https://thumbnails.roblox.com/v1/games/multiget/thumbnails?universeIds=13058&countPerUniverse=1&defaults=true&size=768x432&format=Png&isCircular=false
`{"data":[{"universeId":13058,"error":null,"thumbnails":[{"targetId":696217389,"state":"Completed","imageUrl":"https://tr.rbxcdn.com/e8dff1135d997487a84a813cb4a2de15/768/432/Image/Png"}]}]}`

Actual result: https://legoproxy.veriblox.ml/thumbnails/v1/games/multiget/thumbnails?universeIds=13058&countPerUniverse=1&defaults=true&size=768x432&format=Png&isCircular=false
`{"errors":[{"code":2,"message":"The requested image format is invalid. Please see documentation for valid thumbnail format parameter name and values.","userFacingMessage":"Something went wrong","field":"format"}]}`

**Comment by PyTsun** [comment]
I haven't made LegoProxy to find query parameters yet, will be working on a update right now.

**Comment by PyTsun** [comment]
Query Parameters are now detected on v1.6a
