### ISSUE TITLE
Argo Tunnel error Error 1033. How to use proxy?

### ISSUE THREAD

**Issue by Aerospace911** [PyTsun/LegoProxy#3]
I install the entire github repo, installed all modules, and ran the code. The cmd prompt said 
2024-02-08 23:36:37 INFO        LegoProxy Started!

however, when i try using "https://legoproxy.nyxical.cloud/users.roblox.com/v1/users/1" in the web browser i get that error

when i try https://localhost/users.roblox.com/v1/users/1, I get ERR_SSL_PROTOCOL_ERROR in my browser and (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:992)')) in my cmd prompt

**Comment by nyxical420** [comment]
LegoProxy locally runs on http://localhost:443, the legoproxy on my domain currently does not work since im not running the code on my vps.

**Comment by nyxical420** [comment]
you can also change the localhost port to 8080 from the code if it returns an SSL PROTOCOL ERROR in your browser.
